(function(h){function t(a,b,e){return"rgba("+[Math.round(a[0]+(b[0]-a[0])*e),Math.round(a[1]+(b[1]-a[1])*e),Math.round(a[2]+(b[2]-a[2])*e),a[3]+(b[3]-a[3])*e].join(",")+")"}var u=function(){},o=h.getOptions(),i=h.each,p=h.extend,A=h.format,v=h.pick,q=h.wrap,k=h.Chart,n=h.seriesTypes,w=n.pie,l=n.column,x=HighchartsAdapter.fireEvent,y=HighchartsAdapter.inArray,r=[];p(o.lang,{drillUpText:"◁ Back to {series.name}"});o.drilldown={activeAxisLabelStyle:{cursor:"pointer",color:"#0d233a",fontWeight:"bold",
textDecoration:"underline"},activeDataLabelStyle:{cursor:"pointer",color:"#0d233a",fontWeight:"bold",textDecoration:"underline"},animation:{duration:500},drillUpButton:{position:{align:"right",x:-10,y:10}}};h.SVGRenderer.prototype.Element.prototype.fadeIn=function(a){this.attr({opacity:0.1,visibility:"inherit"}).animate({opacity:v(this.newOpacity,1)},a||{duration:250})};k.prototype.addSeriesAsDrilldown=function(a,b){this.addSingleSeriesAsDrilldown(a,b);this.applyDrilldown()};k.prototype.addSingleSeriesAsDrilldown=
function(a,b){var e=a.series,c=e.xAxis,g=e.yAxis,d;d=a.color||e.color;var f,z=[],h=[],m;m=e.levelNumber||0;b=p({color:d},b);f=y(a,e.points);i(e.chart.series,function(a){if(a.xAxis===c)z.push(a),h.push(a.options),a.levelNumber=a.levelNumber||m});d={levelNumber:m,seriesOptions:e.options,levelSeriesOptions:h,levelSeries:z,shapeArgs:a.shapeArgs,bBox:a.graphic.getBBox(),color:d,lowerSeriesOptions:b,pointOptions:e.options.data[f],pointIndex:f,oldExtremes:{xMin:c&&c.userMin,xMax:c&&c.userMax,yMin:g&&g.userMin,
yMax:g&&g.userMax}};if(!this.drilldownLevels)this.drilldownLevels=[];this.drilldownLevels.push(d);d=d.lowerSeries=this.addSeries(b,!1);d.levelNumber=m+1;if(c)c.oldPos=c.pos,c.userMin=c.userMax=null,g.userMin=g.userMax=null;if(e.type===d.type)d.animate=d.animateDrilldown||u,d.options.animation=!0};k.prototype.applyDrilldown=function(){var a=this.drilldownLevels,b;if(a&&a.length>0)b=a[a.length-1].levelNumber,i(this.drilldownLevels,function(a){a.levelNumber===b&&i(a.levelSeries,function(a){a.levelNumber===
b&&a.remove(!1)})});this.redraw();this.showDrillUpButton()};k.prototype.getDrilldownBackText=function(){var a=this.drilldownLevels;if(a&&a.length>0)return a=a[a.length-1],a.series=a.seriesOptions,A(this.options.lang.drillUpText,a)};k.prototype.showDrillUpButton=function(){var a=this,b=this.getDrilldownBackText(),e=a.options.drilldown.drillUpButton,c,g;this.drillUpButton?this.drillUpButton.attr({text:b}).align():(g=(c=e.theme)&&c.states,this.drillUpButton=this.renderer.button(b,null,null,function(){a.drillUp()},
c,g&&g.hover,g&&g.select).attr({align:e.position.align,zIndex:9}).add().align(e.position,!1,e.relativeTo||"plotBox"))};k.prototype.drillUp=function(){for(var a=this,b=a.drilldownLevels,e=b[b.length-1].levelNumber,c=b.length,g=a.series,d,f,h,j,m=function(b){var c;i(g,function(a){a.options===b&&(c=a)});c=c||a.addSeries(b,!1);if(c.type===h.type&&c.animateDrillupTo)c.animate=c.animateDrillupTo;b===f.seriesOptions&&(j=c)};c--;)if(f=b[c],f.levelNumber===e){b.pop();h=f.lowerSeries;if(!h.chart)for(d=g.length;d--;)if(g[d].options.id===
f.lowerSeriesOptions.id){h=g[d];break}h.xData=[];i(f.levelSeriesOptions,m);x(a,"drillup",{seriesOptions:f.seriesOptions});if(j.type===h.type)j.drilldownLevel=f,j.options.animation=a.options.drilldown.animation,h.animateDrillupFrom&&h.chart&&h.animateDrillupFrom(f);j.levelNumber=e;h.remove(!1);if(j.xAxis)d=f.oldExtremes,j.xAxis.setExtremes(d.xMin,d.xMax,!1),j.yAxis.setExtremes(d.yMin,d.yMax,!1)}this.redraw();this.drilldownLevels.length===0?this.drillUpButton=this.drillUpButton.destroy():this.drillUpButton.attr({text:this.getDrilldownBackText()}).align();
r.length=[]};l.prototype.supportsDrilldown=!0;l.prototype.animateDrillupTo=function(a){if(!a){var b=this,e=b.drilldownLevel;i(this.points,function(a){a.graphic&&a.graphic.hide();a.dataLabel&&a.dataLabel.hide();a.connector&&a.connector.hide()});setTimeout(function(){b.points&&i(b.points,function(a,b){var d=b===(e&&e.pointIndex)?"show":"fadeIn",f=d==="show"?!0:void 0;if(a.graphic)a.graphic[d](f);if(a.dataLabel)a.dataLabel[d](f);if(a.connector)a.connector[d](f)})},Math.max(this.chart.options.drilldown.animation.duration-
50,0));this.animate=u}};l.prototype.animateDrilldown=function(a){var b=this,e=this.chart.drilldownLevels,c=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1].shapeArgs,g=this.chart.options.drilldown.animation,d=this.xAxis;if(!a)i(e,function(a){if(b.options===a.lowerSeriesOptions)c=a.shapeArgs}),c.x+=v(d.oldPos,d.pos)-d.pos,i(this.points,function(a){a.graphic&&a.graphic.attr(c).animate(a.shapeArgs,g);a.dataLabel&&a.dataLabel.fadeIn(g)}),this.animate=null};l.prototype.animateDrillupFrom=
function(a){var b=this.chart.options.drilldown.animation,e=this.group,c=this;i(c.trackerGroups,function(a){if(c[a])c[a].on("mouseover")});delete this.group;i(this.points,function(c){var d=c.graphic,f=h.Color(c.color).rgba,i=h.Color(a.color).rgba,j=function(){d.destroy();e&&(e=e.destroy())};d&&(delete c.graphic,b?d.animate(a.shapeArgs,h.merge(b,{step:function(a,b){b.prop==="start"&&f.length===4&&i.length===4&&this.attr({fill:t(f,i,b.pos)})},complete:j})):(d.attr(a.shapeArgs),j()))})};w&&p(w.prototype,
{supportsDrilldown:!0,animateDrillupTo:l.prototype.animateDrillupTo,animateDrillupFrom:l.prototype.animateDrillupFrom,animateDrilldown:function(a){var b=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],e=this.chart.options.drilldown.animation,c=b.shapeArgs,g=c.start,d=(c.end-g)/this.points.length,f=h.Color(b.color).rgba;if(!a)i(this.points,function(a,b){var i=h.Color(a.color).rgba;a.graphic.attr(h.merge(c,{start:g+b*d,end:g+(b+1)*d}))[e?"animate":"attr"](a.shapeArgs,h.merge(e,{step:function(a,
b){b.prop==="start"&&f.length===4&&i.length===4&&this.attr({fill:t(f,i,b.pos)})}}))}),this.animate=null}});h.Point.prototype.doDrilldown=function(a){for(var b=this.series.chart,e=b.options.drilldown,c=(e.series||[]).length,g;c--&&!g;)e.series[c].id===this.drilldown&&y(this.drilldown,r)===-1&&(g=e.series[c],r.push(this.drilldown));x(b,"drilldown",{point:this,seriesOptions:g});g&&(a?b.addSingleSeriesAsDrilldown(this,g):b.addSeriesAsDrilldown(this,g))};q(h.Point.prototype,"init",function(a,b,e,c){var g=
a.call(this,b,e,c),d=b.chart,f=(a=b.xAxis&&b.xAxis.ticks[c])&&a.label;if(g.drilldown){if(h.addEvent(g,"click",function(){g.doDrilldown()}),f){if(!f.basicStyles)f.basicStyles=h.merge(f.styles);f.addClass("highcharts-drilldown-axis-label").css(d.options.drilldown.activeAxisLabelStyle).on("click",function(){i(f.ddPoints,function(a){a.doDrilldown&&a.doDrilldown(!0)});d.applyDrilldown()});if(!f.ddPoints)f.ddPoints=[];f.ddPoints.push(g)}}else if(f&&f.basicStyles)f.styles={},f.css(f.basicStyles);return g});
q(h.Series.prototype,"drawDataLabels",function(a){var b=this.chart.options.drilldown.activeDataLabelStyle;a.call(this);i(this.points,function(a){if(a.drilldown&&a.dataLabel)a.dataLabel.attr({"class":"highcharts-drilldown-data-label"}).css(b).on("click",function(){a.doDrilldown()})})});var s,o=function(a){a.call(this);i(this.points,function(a){a.drilldown&&a.graphic&&a.graphic.attr({"class":"highcharts-drilldown-point"}).css({cursor:"pointer"})})};for(s in n)n[s].prototype.supportsDrilldown&&q(n[s].prototype,
"drawTracker",o)})(Highcharts);
